name: "Bug Report (NixOS Module)"
description: "Create a bug report against a NixOS Module."
title: "nixos/MODULENAME: BUG TITLE"
labels: ["0.kind: bug", "6.topic: nixos"]
body:
  - type: "markdown"
    attributes:
      value: |
        <p align="center">
          <a href="https://nixos.org">
            <picture>
              <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png">
              <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png">
              <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png" width="500px" alt="NixOS logo">
            </picture>
          </a>
        </p>

        Welcome to Nixpkgs. Please replace the **`nixos/MODULENAME: BUG TITLE`** template above with the correct module name (As seen in the [NixOS Option Search](https://search.nixos.org/options)) and a short title summarising what the bug entails.

        > [!TIP]
        > For instance, if you were filing a bug against the [`systemd-boot`](https://search.nixos.org/options?channel=unstable&show=boot.loader.systemd-boot.enable&from=0&size=1) module about it failing to install `memtest86`, your title would be as follows:
        > `nixos/systemd-boot: fails to install memtest86`

        ---
  - type: "dropdown"
    id: "version"
    attributes:
      label: "NixOS Version"
      description: |
        What version of NixOS are you using?

        > [!IMPORTANT]
        > If you are using an older version, please [update to the latest stable version](https://nixos.org/download) and check if the issue persists before continuing this bug report.
      options:
        - "Please select a version."
        - "- Unstable (25.05)"
        - "- Stable (24.11)"
        - "- Oldstable (24.05)"
      default: 0
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the Bug"
      description: "Please include a clear and concise description of what the issue is."
      placeholder: "`systemd-boot` doesn't install memtest86 if the `boot.loader.systemd-boot.memtest86.enable` option is set to true."
    validations:
      required: true
  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Steps to Reproduce"
      description: "Please include a step-by-step guide for reproducing this issue."
      placeholder: |
        1. Install NixOS on an EFI system with systemd-boot enabled.
        2. Try to enable the `boot.loader.systemd-boot.memtest86.enable` option.
        3. Observe as the memory test option does not appear in the boot menu.
      value: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: "input"
    id: "expected-behaviour"
    attributes:
      label: "Expected Behaviour"
      description: "Please write a consise description of what was supposed to happen."
      placeholder: "`memtest86` would appear in the boot menu."
    validations:
      required: true
  - type: "textarea"
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: |
        If applicable, add screenshots to help explain your problem.
        If you need help uploading images to GitHub, please review the [relevant documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets).
    validations:
      required: false
  - type: "textarea"
    id: "logs"
    attributes:
      label: "Relevant log output"
      description: |
        If applicable, copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: "console"
    validations:
      required: false
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "There are no errors in the `systemd-boot-builder` log."
    validations:
      required: false
  - type: "textarea"
    id: "metadata"
    attributes:
      label: "System Metadata"
      description: "Please run `nix-shell -p nix-info --run \"nix-info -m\"` on a terminal and paste the output of that command here."
      placeholder: |
        - system: `"aarch64-linux"`
        - host os: `Linux 1.0.0, NixOS, 17.09 (Hummingbird), a31ce27`
        - multi-user?: `no`
        - sandbox: `yes`
        - version: `nix-env (Nix) 1.0.0`
        - nixpkgs: `/path/to/nixpkgs`
    validations:
      required: true
  - type: "textarea"
    id: "maintainers"
    attributes:
      label: "Notify Maintainers"
      description: |
        Please mention the people who are in the `meta.maintainers` list of the offending module. This is done by prefixing the person's username with an '@' character. You can quickly go to the source code of a module by searching for it on the [NixOS Option Search](https://search.nixos.org/options) and clicking the "Declared in..." button.

        If in doubt, check `git blame` for whoever last touched the package. Please add the mentions above the `---` characters.
      value: |

        ---

        **Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for Nixpkgs"
      description: |
        This bug tracker is for actionable issues that are not the result of user error. If you need help using your system and are unsure if this is a bug with Nixpkgs/NixOS, please consider asking for help on the [NixOS Discourse](https://discourse.nixos.org/) or the [NixOS Matrix Space](https://matrix.to/#/#community:nixos.org) before opening an issue.

        Please also ensure that this bug report is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues), and that you have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it while communicating in any NixOS space.
      options:
        - label: "I assert that this is a bug and not a support request."
          required: true
        - label: "I assert that this is not a duplicate of any known issue."
          required: true
        - label: "I assert that I have read the Code of Conduct and agree to abide by it."
          required: true
  - type: "markdown"
    attributes:
      value: |
        # Thank you for helping improve NixOS!

        ---
  - type: "textarea"
    id: "priorisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template helps NixOS developers know which issues should be prioritised by allowing users to vote with a :+1: reaction.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps us to figure out what's important to users. Please react on other users' issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
