name: "Module Request"
description: "Create a NixOS Module request for an existing package."
title: "Module Request: nixos/MODULENAME"
labels: ["0.kind: enhancement", "6.topic: nixos", "9.needs: module (new)"]
body:
  - type: "markdown"
    attributes:
      value: |
        <p align="center">
          <a href="https://nixos.org">
            <picture>
              <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png">
              <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png">
              <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png" width="400px" alt="NixOS logo">
            </picture>
          </a>
        </p>

        Welcome to Nixpkgs. Please replace the **`Module Request: nixos/MODULENAME`** template above with the correct module name (As seen in the [NixOS Option Search](https://search.nixos.org/options)).

        > [!TIP]
        > For instance, if you were filing a request against the missing `hello` module, your title would be as follows:
        > `Module Request: nixos/hello`

        ---
  - type: "dropdown"
    id: "version"
    attributes:
      label: "NixOS Version"
      description: |
        What version of NixOS are you using?

        > [!IMPORTANT]
        > If you are using an older or stable version, please update to the latest **unstable** version and check if the module still does not exist before continuing this request.
      options:
        - "Please select a version."
        - "- Unstable (25.05)"
        - "- Stable (24.11)"
        - "- Oldstable (24.05)"
      default: 0
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the Proposed Module"
      description: "Please include a clear and concise description of what the module should accomplish."
      placeholder: "GNU `hello` needs a systemd service to start the server-side Hello World application."
    validations:
      required: true
  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional Context"
      description: "Add any other context about the proposed module here."
      placeholder: "This was originally discussed in the NixOS Hello World Team."
    validations:
      required: false
  - type: "textarea"
    id: "maintainers"
    attributes:
      label: "Notify Maintainers"
      description: |
        Please mention the people who are in the `meta.maintainers` list of the offending module. This is done by prefixing the person's username with an '@' character. You can quickly go to the source code of a module by searching for it on the [NixOS Option Search](https://search.nixos.org/options) and clicking the "Declared in..." button.

        Please note that the maintainer attribute name does not always match the maintainer's GitHub username. If that occurs, try looking in [`maintainers/maintainer-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) for the maintainer attribute name, and checking if the maintainer has a listed GitHub username.

        If in doubt, check `git blame` for whoever last touched the package. Please add the mentions above the `---` characters.
      value: |

        ---

        **Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for Nixpkgs"
      description: |
        This bug tracker is for actionable issues that have not already been resolved. If you believe this module requires additional community feedback and discussion, please consider posting about your module idea on the [NixOS Discourse](https://discourse.nixos.org/) before opening an issue. This should only be necessary for all-encompassing system modules.

        Please also ensure that this bug report is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%229.needs%3A+module+%28new%29%22), and that you have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it while communicating in any NixOS space.
      options:
        - label: "I assert that this module does not yet exist in an open pull request or in NixOS Unstable."
          required: true
        - label: "I assert that this is not a duplicate of any known issue."
          required: true
        - label: "I assert that I have read the Code of Conduct and agree to abide by it."
          required: true
  - type: "markdown"
    attributes:
      value: |
        # Thank you for helping improve NixOS!

        ---
  - type: "textarea"
    id: "priorisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template helps NixOS developers know which issues should be prioritised by allowing users to vote with a :+1: reaction.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps us to figure out what's important to users. Please react on other users' issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
