name: "Update Request"
description: "Create an update request for an existing, but outdated package."
title: "Update Request: PACKAGENAME OLDVERSION → NEWVERSION"
labels: ["0.kind: enhancement", "9.needs: package (update)"]
body:
  - type: "markdown"
    attributes:
      value: |
        <p align="center">
          <a href="https://nixos.org">
            <picture>
              <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png">
              <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png">
              <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/main/public/logo/nixos-hires.png" width="400px" alt="NixOS logo">
            </picture>
          </a>
        </p>

        Welcome to Nixpkgs. Please replace the **`Update Request: PACKAGENAME OLDVERSION → NEWVERSION`** template above with the correct package name (As seen in the [NixOS Package Search](https://search.nixos.org/packages)), the current version of the package, and the latest version of the package.

        > [!TIP]
        > For instance, if you were filing a request against the out of date `hello` package, where the current version in Nixpkgs is 1.0.0, but the latest version upstream is 1.0.1, your title would be as follows:
        > `Update Request: hello 1.0.0 → 1.0.1`

        ---
  - type: "dropdown"
    id: "version"
    attributes:
      label: "NixOS Version"
      description: |
        What version of NixOS are you using?

        > [!IMPORTANT]
        > If you are using an older or stable version, please update to the latest **unstable** version and check if the package is still out of date.
        > If the package has been updated in unstable, but you believe the update should be backported to the stable release of NixOS, please file the '**Request for Backport to Stable**' form instead.
      options:
        - "Please select a version."
        - "- Unstable (25.05)"
        - "- Stable (24.11)"
        - "- Oldstable (24.05)"
      default: 0
    validations:
      required: true
  - type: "input"
    id: "name"
    attributes:
      label: "Package Name"
      description: "Please indicate the name of the package."
      placeholder: "hello"
    validations:
      required: true
  - type: "input"
    id: "upstream-version"
    attributes:
      label: "Upstream Version"
      description: "Please indicate the latest version of the package."
      placeholder: "1.0.1"
    validations:
      required: true
  - type: "textarea"
    id: "nixpkgs-version"
    attributes:
      label: "Nixpkgs Version"
      description: |
        Please indicate the current version number in Nixpkgs' **unstable** channel. You can check this by setting the [NixOS Package Search](https://search.nixos.org/packages?channel=unstable) channel to 'unstable' and searching for the package.
        If you meant to request an upgrade in the stable channel, please file the '**Request for Backport to Stable**' form instead.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: "input"
    id: "changelog"
    attributes:
      label: "Changelog"
      description: "If applicable, please link the upstream changelog for the latest version."
      placeholder: "https://git.savannah.gnu.org/cgit/hello.git/plain/NEWS"
    validations:
      required: false
  - type: "textarea"
    id: "maintainers"
    attributes:
      label: "Notify Maintainers"
      description: |
        Please mention the people who are in the `meta.maintainers` list of the offending package. This is done by prefixing the person's username with an '@' character. You can quickly go to the `meta` attribute set of a package by searching for it on the [NixOS Package Search](https://search.nixos.org/packages) and clicking the "📦 Source" button.

        Please note that the maintainer attribute name does not always match the maintainer's GitHub username. If that occurs, try looking in [`maintainers/maintainer-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) for the maintainer attribute name, and checking if the maintainer has a listed GitHub username.

        If in doubt, check `git blame` for whoever last touched the package. Please add the mentions above the `---` characters.
      value: |

        ---

        **Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)
    validations:
      required: false
  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for Nixpkgs"
      description: |
        This bug tracker is for actionable issues that have not already been resolved. Please ensure that this bug report is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%229.needs%3A+package+%28update%29%22), and that you have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it while communicating in any NixOS space.
      options:
        - label: "I assert that this package update does not yet exist in an open pull request or in NixOS Unstable."
          required: true
        - label: "I assert that this is not a duplicate of any known issue."
          required: true
        - label: "I assert that I have read the Code of Conduct and agree to abide by it."
          required: true
  - type: "markdown"
    attributes:
      value: |
        # Thank you for helping improve NixOS!

        ---
  - type: "textarea"
    id: "priorisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template helps NixOS developers know which issues should be prioritised by allowing users to vote with a :+1: reaction.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps us to figure out what's important to users. Please react on other users' issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
